#!/usr/bin/env ruby
require 'pry'
#Each new term in the Fibonacci sequence is generated by adding the previous two terms.
#By starting with 1 and 2, the first 10 terms will be:
#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#By considering the terms in the Fibonacci sequence whose values do not exceed four million,
#find the sum of the even-valued terms.
sum = 0
def getfib(limit)
  sum = 0
  nums = [1,1]
  loop do
    nums << nums[-1] + nums[-2]
    break if nums.last > limit
    if nums.last % 2 == 0
      sum = sum + nums.last
    end
  end
  return sum
end
try = getfib(4000000)
puts try
