/*The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:
 *
 * 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
 *
 * Let us list the factors of the first seven triangle numbers:
 *
 *  1: 1
 *   3: 1,3
 *    6: 1,2,3,6
 *    10: 1,2,5,10
 *    15: 1,3,5,15
 *    21: 1,3,7,21
 *    28: 1,2,4,7,14,28
 *    We can see that 28 is the first triangle number to have over five divisors.
 *
 *    What is the value of the first triangle number to have over five hundred divisors? */
#include<stdio.h>
#include<math.h>

int count_factors(int num){
  int i;
  int count = 0;
  int lim = floor(sqrt(num));
  for(i = 1;i <= lim;++i){
    if((num % i) == 0)
      ++count;
  }
  return (count * 2);
}

int main(void){
  int num = 1;
  int find = 500;
  int tri_num, count = 0;
  int best = 0;
  do{
    ++num;
    tri_num = num * (num + 1) / 2;
    count = count_factors(tri_num);
    if (count > best){
      best = count;
    }
    printf("# of factors for %d: %d (best: %d)\n", tri_num, count, best);
  }while (count <= find);
}
